// nodes.js — Laravel plugin node types

module.exports = [
  {
    id: 'laravel_model',
    label: 'Model',
    description: 'Eloquent model',
    color: '#10b981',
    icon: '◈',
    deletable: false,
    renameable: false,
    openable: true,
  },
  {
    id: 'laravel_controller',
    label: 'Controller',
    description: 'HTTP Controller',
    color: '#3b82f6',
    icon: '⬢',
    deletable: false,
    renameable: false,
    openable: true,
  },
  {
    id: 'laravel_route_group',
    label: 'Route Group',
    description: 'Route file or prefix group',
    color: '#6d28d9',
    icon: '▤',
    deletable: false,
    renameable: false,
    openable: true,
  },
  {
    id: 'laravel_migration',
    label: 'Migration',
    description: 'Database migration',
    color: '#f59e0b',
    icon: '◧',
    deletable: false,
    renameable: false,
    openable: true,
  },
  {
    id: 'laravel_middleware',
    label: 'Middleware',
    description: 'HTTP Middleware',
    color: '#eab308',
    icon: '⊗',
    deletable: false,
    renameable: false,
    openable: true,
  },
  {
    id: 'laravel_service',
    label: 'Service',
    description: 'Service class',
    color: '#06b6d4',
    icon: '◆',
    deletable: false,
    renameable: false,
    openable: true,
  },
  {
    id: 'laravel_provider',
    label: 'Provider',
    description: 'Service Provider',
    color: '#f97316',
    icon: '◉',
    deletable: false,
    renameable: false,
    openable: true,
  },
  {
    id: 'laravel_job',
    label: 'Job',
    description: 'Queued Job',
    color: '#6b7280',
    icon: '⚙',
    deletable: false,
    renameable: false,
    openable: true,
  },
  {
    id: 'laravel_event',
    label: 'Event',
    description: 'Application Event',
    color: '#14b8a6',
    icon: '◈',
    deletable: false,
    renameable: false,
    openable: true,
  },
];
